@Negotiations.API_HostAddress = https://localhost:7289
@productId = 1



GET {{Negotiations.API_HostAddress}}/api/products

###


GET {{Negotiations.API_HostAddress}}/api/products/{{productId}}

###


GET {{Negotiations.API_HostAddress}}/api/products/{{productId}}/negotiation

###

POST {{Negotiations.API_HostAddress}}/api/products
Content-Type: application/json

{
  "Name": "Product 3",
  "Price": 100.04
}

###

DELETE {{Negotiations.API_HostAddress}}/api/products/{{productId}}

###

POST {{Negotiations.API_HostAddress}}/api/products/{{productId}}/negotiation
Content-Type: application/json

{
  "SuggestedPrice": 200
}

###
